-- ============================================================
-- TOTAL REVENUE PER PRODUCT
-- Total revenue per product (ID + timestamp + name)
-- Sorted by highest revenue
-- ============================================================
SELECT product_id, scraped_at, name, ROUND(SUM(sales_volume*price),2) AS total_sales_usd
FROM zara_fact
GROUP BY product_id, scraped_at, name
ORDER BY total_sales_usd DESC;

-- ============================================================
-- BOTTOM 5 PRODUCTS BY REVENUE
-- 5 products with the lowest total revenue
-- ============================================================
SELECT product_id, scraped_at, name, ROUND(SUM(sales_volume*price),2) AS total_sales_usd
FROM zara_fact
GROUP BY product_id, scraped_at, name
ORDER BY total_sales_usd ASC 
LIMIT 5;

-- ============================================================
-- TOP 5 PRODUCTS BY REVENUE
-- 5 products with the highest total revenue
-- ============================================================
SELECT product_id, scraped_at, name, ROUND(SUM(sales_volume*price),2) AS total_sales_usd
FROM zara_fact
GROUP BY product_id, scraped_at, name
ORDER BY total_sales_usd DESC
LIMIT 5;

-- ============================================================
-- REVENUE PER PRODUCT POSITION (IN MILLIONS)
-- Revenue per product_position (in millions USD)
-- + how many times each position is smaller vs the top position
-- ============================================================
SELECT product_position, revenue_per_position_MIL_USD,
ROUND(MAX(revenue_per_position_MIL_USD) OVER() / revenue_per_position_MIL_USD,1) AS times_vs_top_position
FROM (
SELECT product_position,
           ROUND(SUM(sales_volume*price)/1000000,2) AS revenue_per_position_MIL_USD
FROM zara_fact
GROUP BY product_position
ORDER BY revenue_per_position_MIL_USD DESC
) t;

-- ============================================================
-- PROMOTION REVENUE SHARE (%)
-- Share of revenue generated by promoted vs non-promoted items
-- ============================================================
SELECT 
ROUND(SUM(sales_volume*price)/1000000,2) AS total_revenue_MIL_USD,
ROUND(SUM(CASE WHEN promotion = 'No'  THEN price*sales_volume ELSE 0 END) 
          / SUM(price*sales_volume) * 100,1) AS promo_no_pct,
ROUND(SUM(CASE WHEN promotion = 'Yes' THEN price*sales_volume ELSE 0 END) 
          / SUM(price*sales_volume) * 100,1) AS promo_yes_pct
FROM zara_fact;

-- ============================================================
-- AVERAGE PRICE BY GENDER + SHARE (%)
-- Average price per gender section + percentage contribution
-- ============================================================
WITH cte AS (
SELECT section, AVG(price) AS Avg_Sales_per_gender_USD
FROM zara_fact
GROUP BY section
)
SELECT section, Avg_Sales_per_gender_USD,
       ROUND(Avg_Sales_per_gender_USD / SUM(Avg_Sales_per_gender_USD) OVER () * 100,1) AS percent_of_total
FROM cte;

-- ============================================================
-- SALES BY TERMS + SHARE (%)
-- Revenue (in millions USD) per terms category + percentage share
-- ============================================================
WITH cte AS (
SELECT terms, ROUND(SUM(sales_volume*price)/1000000,1) AS sales_by_terms_in_millions
FROM zara_fact
GROUP BY terms
)
SELECT terms, sales_by_terms_in_millions, 
ROUND(sales_by_terms_in_millions / SUM(sales_by_terms_in_millions) OVER() * 100,1) AS percent_of_terms
FROM cte
ORDER BY percent_of_terms DESC;

-- ============================================================
-- TOP PRODUCTS ≥150 USD WITHIN EACH TERMS CATEGORY
-- Ranking products (≥150 USD) within each terms category by revenue
-- ============================================================
SELECT product_position, seasonal, name, sales_volume, price, terms, sales_volume*price AS total,
DENSE_RANK() OVER (PARTITION BY terms ORDER BY sales_volume*price DESC) AS rnk
FROM zara_fact
WHERE price >= 150
ORDER BY terms, rnk;

-- ============================================================
-- ABSOLUTE BESTSELLER (HIGHEST TOTAL REVENUE)
-- Product with the highest revenue (sales_volume * price)
-- ============================================================
SELECT 
    product_id, product_position, promotion, product_category, 
    seasonal, sku, name, terms, sales_volume*price AS total_revenue
FROM zara_fact
ORDER BY total_revenue DESC
LIMIT 1;

-- ============================================================
-- MOST EXPENSIVE ITEM (BY UNIT PRICE)
-- Product with the highest individual price
-- ============================================================
SELECT 
    product_id, product_position, promotion, product_category,
    seasonal, sku, name, terms, sales_volume, price,
    sales_volume*price AS most_exp_item_revenue
FROM zara_fact
ORDER BY price DESC
LIMIT 1;
